export const ItemListData = [
  {
    itemName: "Linsensuppe",
    price: 5.5,
    itemId: "1",
    category: "Suppen",
  },
  {
    itemName: "Tomatensuppe",
    price: 5.5,
    itemId: "2",
    category: "Suppen",
  },
  {
    itemName: "Hühnersuppe",
    price: 6.5,
    itemId: "3",
    category: "Suppen",
  },
  {
    itemName: "Pappadums & Chutneys",
    price: 3,
    itemId: "6",
    category: "Indische Vorspeisen",
  },
  {
    itemName: "Samosa ",
    price: 7,
    itemId: "7",
    category: "Indische Vorspeisen",
  },
  {
    itemName: "Mixed Vegetable Pakora Platter",
    price: 8.5,
    itemId: "8",
    category: "Indische Vorspeisen",
  },
  {
    itemName: "Cheese Pakora Teller",
    price: 9.5,
    itemId: "9",
    category: "Indische Vorspeisen",
  },
  {
    itemName: "Chicken Pakora Teller",
    price: 9.5,
    itemId: "10",
    category: "Indische Vorspeisen",
  },
  {
    itemName: "Gemischter Vorspeisenteller",
    price: 14,
    itemId: "12",
    category: "Indische Vorspeisen",
  },
  {
    itemName: "Onion Baji",
    price: 8,
    itemId: "13",
    category: "Indische Vorspeisen",
  },
  {
    itemName: "FischPakora",
    price: 10,
    itemId: "14",
    category: "Indische Vorspeisen",
  },
  {
    itemName: "Chili Mushroom",
    price: 9.5,
    itemId: "15",
    category: "Indische Vorspeisen",
  },
  {
    itemName: "Honey Chili Pommes",
    price: 9.5,
    itemId: "16",
    category: "Indische Vorspeisen",
  },
  {
    itemName: "Panierte Scampis mit Pommes",
    price: 13,
    itemId: "17",
    category: "Indische Vorspeisen",
  },
  {
    itemName: "Panierte Champignons mit Knoblauchsauce",
    price: 15,
    itemId: "18",
    category: "Indische Vorspeisen",
  },
  {
    itemName: "Beilagensalat",
    price: 4.5,
    itemId: "19",
    category: "Salate",
  },
  {
    itemName: "Gemischter Salat",
    price: 8,
    itemId: "20",
    category: "Salate",
  },
  {
    itemName: "Prawn Salat",
    price: 17,
    itemId: "21",
    category: "Salate",
  },
  {
    itemName: "Paneer Salat",
    price: 15,
    itemId: "22",
    category: "Salate",
  },
  {
    itemName: "Indian Tadka - Spezial Salat",
    price: 15,
    itemId: "23",
    category: "Salate",
  },
  {
    itemName: "Butter Naan",
    price: 4,
    itemId: "27",
    category: "Spezialitätenbrote",
  },
  {
    itemName: "Garlic Naan",
    price: 4.5,
    itemId: "28",
    category: "Spezialitätenbrote",
  },
  {
    itemName: "Keema Naan",
    price: 6.5,
    itemId: "29",
    category: "Spezialitätenbrote",
  },
  {
    itemName: "Paneer Naan",
    price: 6.5,
    itemId: "30",
    category: "Spezialitätenbrote",
  },
  {
    itemName: "Aloo Kulcha",
    price: 5.5,
    itemId: "32",
    category: "Spezialitätenbrote",
  },
  {
    itemName: "Tandoori Roti",
    price: 3.5,
    itemId: "33",
    category: "Spezialitätenbrote",
  },
  {
    itemName: "Pishwari Naan",
    price: 6.5,
    itemId: "33a",
    category: "Spezialitätenbrote",
  },
  {
    itemName: "Fisch Tikka ",
    price: 17.5,
    itemId: "34",
    category: "Tandoori Spezialitäten",
  },
  {
    itemName: "Chicken Tikka",
    price: 16.5,
    itemId: "35",
    category: "Tandoori Spezialitäten",
  },
  {
    itemName: "Haryali Chicken Tikka ",
    price: 16.5,
    itemId: "36",
    category: "Tandoori Spezialitäten",
  },
  {
    itemName: "Malai Tikka ",
    price: 16.5,
    itemId: "37",
    category: "Tandoori Spezialitäten",
  },
  {
    itemName: "Garlic Chicken Tikka ",
    price: 16.5,
    itemId: "38",
    category: "Tandoori Spezialitäten",
  },
  {
    itemName: "Punjabi Paneer Tikka",
    price: 17,
    itemId: "39",
    category: "Tandoori Spezialitäten",
  },
  {
    itemName: "Tandoori Prawns",
    price: 22.5,
    itemId: "40",
    category: "Tandoori Spezialitäten",
  },
  {
    itemName: "Indian Tadka Grill Platte",
    price: 25,
    itemId: "41",
    category: "Tandoori Spezialitäten",
  },
  {
    itemName: "Tandoori Chicken ",
    price: 17.5,
    itemId: "42",
    category: "Tandoori Spezialitäten",
  },
  {
    itemName: "Chicken Palak",
    price: 15.5,
    itemId: "170",
    category: "Indische Hähnchenspezialitäten",
  },
  {
    itemName: "Chicken Dhansak",
    price: 15.5,
    itemId: "171",
    category: "Indische Hähnchenspezialitäten",
  },
  {
    itemName: "Chicken Madras",
    price: 15.5,
    itemId: "172",
    category: "Indische Hähnchenspezialitäten",
  },
  {
    itemName: "Chicken Curry",
    price: 15.5,
    itemId: "173",
    category: "Indische Hähnchenspezialitäten",
  },
  {
    itemName: "Chicken Tikka Masala",
    price: 15.5,
    itemId: "174",
    category: "Indische Hähnchenspezialitäten",
  },
  {
    itemName: "Butter Chicken",
    price: 15.5,
    itemId: "175",
    category: "Indische Hähnchenspezialitäten",
  },
  {
    itemName: "Chicken Korma",
    price: 15.5,
    itemId: "176",
    category: "Indische Hähnchenspezialitäten",
  },
  {
    itemName: "Chicken Jalfrezi",
    price: 15.5,
    itemId: "177",
    category: "Indische Hähnchenspezialitäten",
  },
  {
    itemName: "Chicken Vindaloo",
    price: 15.5,
    itemId: "178",
    category: "Indische Hähnchenspezialitäten",
  },
  {
    itemName: "Chili Chicken",
    price: 15.5,
    itemId: "179",
    category: "Indische Hähnchenspezialitäten",
  },
  {
    itemName: "Mango Chicken",
    price: 15.5,
    itemId: "180",
    category: "Indische Hähnchenspezialitäten",
  },
  {
    itemName: "Karahi Chicken",
    price: 15.5,
    itemId: "181",
    category: "Indische Hähnchenspezialitäten",
  },
  {
    itemName: "Chicken Curry Lounge",
    price: 16.5,
    itemId: "182",
    category: "Indische Hähnchenspezialitäten",
  },
  {
    itemName: "Fish Chili",
    price: 17.5,
    itemId: "71",
    category: "Fischspezialitäten",
  },
  {
    itemName: "Fish Masala",
    price: 17.5,
    itemId: "72",
    category: "Fischspezialitäten",
  },
  {
    itemName: "Jheenga Vindaloo",
    price: 19.5,
    itemId: "73",
    category: "Fischspezialitäten",
  },
  {
    itemName: "Jheenga Masala",
    price: 19.5,
    itemId: "74",
    category: "Fischspezialitäten",
  },
  {
    itemName: "Fish Curry Lounge",
    price: 18,
    itemId: "75",
    category: "Fischspezialitäten",
  },
  {
    itemName: "Lammcurry",
    price: 18,
    itemId: "76",
    category: "Lammspezialitäten",
  },
  {
    itemName: "Lamm Korma",
    price: 18,
    itemId: "76a",
    category: "Lammspezialitäten",
  },
  {
    itemName: "Lamm Vindaloo",
    price: 18,
    itemId: "77",
    category: "Lammspezialitäten",
  },
  {
    itemName: "Lamm Palak",
    price: 18,
    itemId: "77a",
    category: "Lammspezialitäten",
  },
  {
    itemName: "Lamm Madras",
    price: 18,
    itemId: "78",
    category: "Lammspezialitäten",
  },
  {
    itemName: "Lamm Karahi",
    price: 18,
    itemId: "79",
    category: "Lammspezialitäten",
  },
  {
    itemName: "Lamm Jalfrezi",
    price: 18,
    itemId: "80",
    category: "Lammspezialitäten",
  },
  {
    itemName: "Lamm Curry Lounge",
    price: 18,
    itemId: "80a",
    category: "Lammspezialitäten",
  },
  {
    itemName: "Lamm Tikka Masala",
    price: 18,
    itemId: "91",
    category: "Lammspezialitäten",
  },
  {
    itemName: "Lamm Sweet Chilli",
    price: 18,
    itemId: "92",
    category: "Lammspezialitäten",
  },
  {
    itemName: "Lamm Rogan Josh",
    price: 18,
    itemId: "93",
    category: "Lammspezialitäten",
  },
  {
    itemName: "Vegetarisch Biryani",
    price: 14.5,
    itemId: "85",
    category: "Biryani Basmati-Reis-Spezialitäten",
  },
  {
    itemName: "Murgh Biryani",
    price: 15,
    itemId: "86",
    category: "Biryani Basmati-Reis-Spezialitäten",
  },
  {
    itemName: "Lamm Biryani",
    price: 17,
    itemId: "87",
    category: "Biryani Basmati-Reis-Spezialitäten",
  },
  {
    itemName: "Jheenga Biryani",
    price: 17.5,
    itemId: "88",
    category: "Biryani Basmati-Reis-Spezialitäten",
  },
  {
    itemName: "Rajma Masala",
    price: 14.5,
    itemId: "43",
    category: "Indische Spezialitäten Vegetarisch",
  },
  {
    itemName: "Dal Makhni",
    price: 14.5,
    itemId: "45",
    category: "Indische Spezialitäten Vegetarisch",
  },
  {
    itemName: "Dal Tarka",
    price: 14.5,
    itemId: "46",
    category: "Indische Spezialitäten Vegetarisch",
  },
  {
    itemName: "Aloo Chana Masala",
    price: 14.5,
    itemId: "47",
    category: "Indische Spezialitäten Vegetarisch",
  },
  {
    itemName: "Veg. Jalfrezi",
    price: 14.5,
    itemId: "48",
    category: "Indische Spezialitäten Vegetarisch",
  },
  {
    itemName: "Palak Paneer",
    price: 15.5,
    itemId: "49",
    category: "Indische Spezialitäten Vegetarisch",
  },
  {
    itemName: "Matar Paneer",
    price: 15.5,
    itemId: "52",
    category: "Indische Spezialitäten Vegetarisch",
  },
  {
    itemName: "Shahi Paneer",
    price: 15.5,
    itemId: "53",
    category: "Indische Spezialitäten Vegetarisch",
  },
  {
    itemName: "Chili Paneer",
    price: 15.5,
    itemId: "54",
    category: "Indische Spezialitäten Vegetarisch",
  },
  {
    itemName: "Baingan Bharta",
    price: 14.5,
    itemId: "54a",
    category: "Indische Spezialitäten Vegetarisch",
  },
  {
    itemName: "Bhindi Sabji (Seasonal)",
    price: 14.5,
    itemId: "54b",
    category: "Indische Spezialitäten Vegetarisch",
  },
  {
    itemName: "Veg Korma",
    price: 14.5,
    itemId: "54c",
    category: "Indische Spezialitäten Vegetarisch",
  },
  {
    itemName: "Aloo Gobi",
    price: 14.5,
    itemId: "54d",
    category: "Indische Spezialitäten Vegetarisch",
  },
  {
    itemName: "Karahi Paneer",
    price: 15.5,
    itemId: "55",
    category: "Indische Spezialitäten Vegetarisch",
  },
  {
    itemName: "Paneer Tikka Masala",
    price: 15.5,
    itemId: "55a",
    category: "Indische Spezialitäten Vegetarisch",
  },
  {
    itemName: "Reis (Rice)",
    price: 2.5,
    itemId: "55b",
    category: "Indische Spezialitäten Vegetarisch",
  },
  {
    itemName: "Mozzarella Sticks",
    price: 9.5,
    itemId: "110",
    category: "Kinder Menü",
  },
  {
    itemName: "Crispy Burger Menü mit Pommes",
    price: 9.5,
    itemId: "111",
    category: "Kinder Menü",
  },
  {
    itemName: "Chicken Nuggets",
    price: 7,
    itemId: "112",
    category: "Kinder Menü",
  },
  {
    itemName: "Pommes frites",
    price: 4,
    itemId: "113",
    category: "Kinder Menü",
  },
  {
    itemName: "Schnitzel Wiener Art",
    price: 14,
    itemId: "100",
    category: "Fleischgerichte",
  },
  {
    itemName: "Zigeunerschnitzel",
    price: 15,
    itemId: "101",
    category: "Fleischgerichte",
  },
  {
    itemName: "Rahmschnitzel mit Champignons",
    price: 15.5,
    itemId: "102",
    category: "Fleischgerichte",
  },
  {
    itemName: "Pfefferschnitzel",
    price: 15,
    itemId: "103",
    category: "Fleischgerichte",
  },
  {
    itemName: "Prosciutto Schnitzel",
    price: 16,
    itemId: "105",
    category: "Fleischgerichte",
  },
  {
    itemName: "Gulab Jamun",
    price: 4,
    itemId: "120",
    category: "Dessert-Menü",
  },
  {
    itemName: "Firni",
    price: 5.5,
    itemId: "121",
    category: "Dessert-Menü",
  },
  {
    itemName: "Spezial Eisbecher",
    price: 7.5,
    itemId: "122",
    category: "Dessert-Menü",
  },
  {
    itemName: "Schokokuss",
    price: 7,
    itemId: "123",
    category: "Dessert-Menü",
  },
  {
    itemName: "Spezial Eisbecher (mit Sahne)",
    price: 8.5,
    itemId: "124",
    category: "Dessert-Menü",
  },
  {
    itemName: "Campari Soda oder Orange Longdrink",
    price: 5.5,
    itemId: "201",
    category: "Aperitif",
  },
  {
    itemName: "Pernod mit Naturwasser, 2cl",
    price: 3,
    itemId: "202",
    category: "Aperitif",
  },
  {
    itemName: "Martini Rosso oder Bianco 5cl",
    price: 3.5,
    itemId: "203",
    category: "Aperitif",
  },
  {
    itemName: "Sherry Dry oder Medium 5cl",
    price: 3.5,
    itemId: "204",
    category: "Aperitif",
  },
  {
    itemName: "Prosecco 0,1",
    price: 4,
    itemId: "205",
    category: "Aperitif",
  },
  {
    itemName: "Prosecco Aperol Spritz ",
    price: 6,
    itemId: "206",
    category: "Aperitif",
  },
  {
    itemName: "Prosecco mit Waldbeerenlikör",
    price: 6,
    itemId: "207",
    category: "Aperitif",
  },
  {
    itemName: "Hugo - Cocktail",
    price: 6,
    itemId: "208",
    category: "Aperitif",
  },
  {
    itemName: "Lassi (Salz und Pfeffer)",
    price: 4,
    itemId: "209",
    category: "Indische Kaltgetränke",
  },
  {
    itemName: "Mango Lassi",
    price: 4.5,
    itemId: "210",
    category: "Indische Kaltgetränke",
  },
  {
    itemName: "Mango Saft, Orangen saft 0,2",
    price: 2.5,
    itemId: "211",
    category: "Alkoholfreie Getränke ",
  },
  {
    itemName: "Mango Saft, Orangen saft 0,4",
    price: 4.5,
    itemId: "211",
    category: "Alkoholfreie Getränke ",
  },
  {
    itemName: "Mango Milk Shake",
    price: 5,
    itemId: "213",
    category: "Alkoholfreie Getränke ",
  },
  {
    itemName: "Bitburger vom Fass 0,5",
    price: 4.5,
    itemId: "214",
    category: "Biere ",
  },
  {
    itemName: "Bitburger vom Fass 0,25",
    price: 3.5,
    itemId: "214",
    category: "Biere ",
  },
  {
    itemName: "Bitburger alkoholfrei 0,3",
    price: 3.5,
    itemId: "216",
    category: "Biere ",
  },
  {
    itemName: "King Fisher 0,33",
    price: 4,
    itemId: "217",
    category: "Biere ",
  },
  {
    itemName: "Energy-Drink 0.25",
    price: 3.5,
    itemId: "218",
    category: "Biere ",
  },
  {
    itemName: "Radler 0.25",
    price: 3.5,
    itemId: "219",
    category: "Biere ",
  },
  {
    itemName: "Radler 0.5",
    price: 4.5,
    itemId: "219",
    category: "Biere ",
  },
  {
    itemName: "Weizenbier ",
    price: 4.5,
    itemId: "221",
    category: "Biere ",
  },
  {
    itemName: "Alkoholfreie Weizenbier",
    price: 4.5,
    itemId: "222",
    category: "Alkoholfreie Getränke ",
  },
  {
    itemName: "Soave Weißwein 0,25",
    price: 6,
    itemId: "223",
    category: "Weine  ",
  },
  {
    itemName: "Pinot Grigio 0,25",
    price: 6,
    itemId: "224",
    category: "Weine  ",
  },
  {
    itemName: "Rosé di Veneto 0,25",
    price: 6,
    itemId: "225",
    category: "Weine  ",
  },
  {
    itemName: "Lambrusco 0,25",
    price: 6,
    itemId: "226",
    category: "Weine  ",
  },
  {
    itemName: "Barbera 0,25",
    price: 6,
    itemId: "227",
    category: "Weine  ",
  },
  {
    itemName: "Montepulciano 0,25",
    price: 6,
    itemId: "262",
    category: "Weine  ",
  },
  {
    itemName: "Weinschorle (rot oder weiß) ",
    price: 5.5,
    itemId: "228",
    category: "Weine  ",
  },
  {
    itemName: "Ouzo",
    price: 2.5,
    itemId: "229",
    category: "Spirituosen / Liköre",
  },
  {
    itemName: "Limoncello",
    price: 2.5,
    itemId: "230",
    category: "Spirituosen / Liköre",
  },
  {
    itemName: "Sambuca Molinari",
    price: 3,
    itemId: "231",
    category: "Spirituosen / Liköre",
  },
  {
    itemName: "Baileys",
    price: 3,
    itemId: "232",
    category: "Spirituosen / Liköre",
  },
  {
    itemName: "Haselnuss Schnaps",
    price: 3.5,
    itemId: "233",
    category: "Spirituosen / Liköre",
  },
  {
    itemName: "Jägermeister",
    price: 3.5,
    itemId: "234",
    category: "Spirituosen / Liköre",
  },
  {
    itemName: "Jack Daniels - Longdrink",
    price: 4.5,
    itemId: "235",
    category: "Spirituosen / Liköre",
  },
  {
    itemName: "Grappa",
    price: 3,
    itemId: "236",
    category: "Spirituosen / Liköre",
  },
  {
    itemName: "Tequila",
    price: 3.5,
    itemId: "263",
    category: "Spirituosen / Liköre",
  },
  {
    itemName: "Chivas",
    price: 3.5,
    itemId: "237",
    category: "Whisky",
  },
  {
    itemName: "Black Label",
    price: 3.5,
    itemId: "238",
    category: "Whisky",
  },
  {
    itemName: "JimBeam Cola",
    price: 3.5,
    itemId: "239",
    category: "Whisky",
  },
  {
    itemName: "Indischer Old Mog Rum",
    price: 3.5,
    itemId: "240",
    category: "Whisky",
  },
  {
    itemName: "Jacky (Whiskey)",
    price: 3.5,
    itemId: "241",
    category: "Whisky",
  },
  {
    itemName: "Red Label (Whiskey)",
    price: 3.5,
    itemId: "242",
    category: "Whisky",
  },
  {
    itemName: "Indischer Tee",
    price: 3.5,
    itemId: "243",
    category: "Warme Getränke ",
  },
  {
    itemName: "Espresso",
    price: 2.2,
    itemId: "244",
    category: "Warme Getränke ",
  },
  {
    itemName: "Kaffee",
    price: 3,
    itemId: "245",
    category: "Warme Getränke ",
  },
  {
    itemName: "Cappuccino",
    price: 4,
    itemId: "246",
    category: "Warme Getränke ",
  },
  {
    itemName: "Kakao",
    price: 3,
    itemId: "247",
    category: "Warme Getränke ",
  },
  {
    itemName: "Kakao mit sahne",
    price: 3.5,
    itemId: "248",
    category: "Warme Getränke ",
  },
  {
    itemName: "Latte Macchiato",
    price: 4,
    itemId: "249",
    category: "Warme Getränke ",
  },
  {
    itemName: "Tee (verschiedene Sorten)",
    price: 2.5,
    itemId: "250",
    category: "Warme Getränke ",
  },
  {
    itemName: "Fanta / Sprite 0,2",
    price: 3,
    itemId: "251",
    category: "Alkoholfreie Getränke ",
  },
  {
    itemName: "Fanta / Sprite 0,4",
    price: 4,
    itemId: "251a",
    category: "Alkoholfreie Getränke ",
  },
  {
    itemName: "CocaCola / CocaCola Zero 0,2",
    price: 3,
    itemId: "253",
    category: "Alkoholfreie Getränke ",
  },
  {
    itemName: "CocaCola / CocaCola Zero 0,4",
    price: 4,
    itemId: "253a",
    category: "Alkoholfreie Getränke ",
  },
  {
    itemName: "Apfelsaftschorle 0,3",
    price: 3,
    itemId: "255",
    category: "Alkoholfreie Getränke ",
  },
  {
    itemName: "Apfelsaftschorle 0,4",
    price: 4,
    itemId: "255a",
    category: "Alkoholfreie Getränke ",
  },
  {
    itemName: "Mineralwasser / Stilles Wasser 0,25",
    price: 2,
    itemId: "257",
    category: "Alkoholfreie Getränke ",
  },
  {
    itemName: "Mineralwasser / Stilles Wasser 0,75",
    price: 5,
    itemId: "257a",
    category: "Alkoholfreie Getränke ",
  },
  {
    itemName: "Apfelsaft 0,2",
    price: 3.5,
    itemId: "259",
    category: "Alkoholfreie Getränke ",
  },
  {
    itemName: "Apfelsaft 0,4",
    price: 4.5,
    itemId: "259a",
    category: "Alkoholfreie Getränke ",
  },
  {
    itemName: "Bitter Lemon (Schweppes)",
    price: 2.5,
    itemId: "261",
    category: "Alkoholfreie Getränke ",
  },
  {
    itemName: "Chicken Curry (Mittagsmenü)",
    price: 8.9,
    itemId: "M1",
    category: "Mittagsmenü",
  },
  {
    itemName: "Veg. Jalfrezi (Mittagsmenü)",
    price: 8,
    itemId: "M2",
    category: "Mittagsmenü",
  },
  {
    itemName: "Chicken Jalfrezi (Mittagsmenü)",
    price: 8.9,
    itemId: "M3",
    category: "Mittagsmenü",
  },
  {
    itemName: "Fish Curry (Mittagsmenü)",
    price: 9.9,
    itemId: "M4",
    category: "Mittagsmenü",
  },
  {
    itemName: "Aloo Gobi Mutter (VEGAN) (Mittagsmenü)",
    price: 8,
    itemId: "M5",
    category: "Mittagsmenü",
  },
  {
    itemName: "Methi Chicken (Mittagsmenü)",
    price: 8.9,
    itemId: "M6",
    category: "Mittagsmenü",
  },
  {
    itemName: "Butter Chicken (Mittagsmenü)",
    price: 8.9,
    itemId: "M7",
    category: "Mittagsmenü",
  },
  {
    itemName: "Chicken Madras (Mittagsmenü)",
    price: 8.9,
    itemId: "M8",
    category: "Mittagsmenü",
  },
  {
    itemName: "Palak Paneer (Mittagsmenü)",
    price: 8.9,
    itemId: "M9",
    category: "Mittagsmenü",
  },
  {
    itemName: "Balti Chicken (Mittagsmenü)",
    price: 8.9,
    itemId: "M10",
    category: "Mittagsmenü",
  },
  {
    itemName: "Palak Chicken (Mittagsmenü)",
    price: 8.9,
    itemId: "M11",
    category: "Mittagsmenü",
  },
  {
    itemName: "Paneer Makhani (Mittagsmenü)",
    price: 8.9,
    itemId: "M12",
    category: "Mittagsmenü",
  },
  {
    itemName: "salat (Mittagsmenü)",
    price: 3.5,
    itemId: "M13",
    category: "Mittagsmenü",
  },
  {
    itemName: "Liefer",
    price: 1,
    itemId: "0001",
    category: "Delivery",
  },
];
