export const ItemListData = [
    {
      itemId: 1,
      category: 'indische_vorspeisen',
      itemName: 'Samosa',
      description: 'Gefüllte Teigtaschen mit Kartoffeln und Erbsen',
      price: 6.50,
      allergies: 'Kann Weizen enthalten',
    },
    {
      itemId: 2,
      category: 'indische_vorspeisen',
      itemName: 'Mixed Vegetable Pakora Platter',
      description: '2 Aloo Pakora, 2 Zucchini, 2 Aubergine, 4 Onion Rings',
      price: 8.50,
      allergies: 'Enthält Kichererbsenmehl',
    },
    {
      itemId: 3,
      category: 'indische_vorspeisen',
      itemName: 'Cheese Pakora Teller',
      description: 'Hausgemachter indischer Käse, paniert und mit Kichererbsenmehl ausgebacken',
      price: 9.50,
      allergies: 'Enthält Kichererbsenmehl, Milchprodukte',
    },
    {
      itemId: 4,
      category: 'salate',
      itemName: 'Gemischter Salat',
      description: 'Frische Blattsalate mit Tomaten, Gurken und Paprika',
      price: 5.50,
      allergies: 'Kann Spuren von Nüssen enthalten',
    },
    {
      itemId: 5,
      category: 'salate',
      itemName: 'Chicken Tikka Salat',
      description: 'Gegrilltes Hähnchenbrustfilet auf gemischtem Salat',
      price: 10.50,
      allergies: 'Keine angegeben',
    },
    {
      itemId: 6,
      category: 'hauptspeisen',
      itemName: 'Butter Chicken',
      description: 'Hähnchenstücke in einer milden Tomaten-Butter-Sahnesoße',
      price: 14.50,
      allergies: 'Enthält Milchprodukte',
    },
    {
      itemId: 7,
      category: 'hauptspeisen',
      itemName: 'Vegetarisches Curry',
      description: 'Frisches Gemüse in würziger Currysauce',
      price: 12.50,
      allergies: 'Kann Spuren von Nüssen enthalten',
    },
    {
      itemId: 8,
      category: 'desserts',
      itemName: 'Gulab Jamun',
      description: 'Frittierte Teigbällchen in Zuckersirup',
      price: 4.50,
      allergies: 'Enthält Milchprodukte, Weizen',
    },
    {
      itemId: 9,
      category: 'desserts',
      itemName: 'Mango Kulfi',
      description: 'Indisches Mango-Eis',
      price: 5.50,
      allergies: 'Enthält Milchprodukte',
    },
    {
      itemId: 10,
      category: 'getränke',
      itemName: 'Mango Lassi',
      description: 'Joghurtgetränk mit Mango',
      price: 3.50,
      allergies: 'Enthält Milchprodukte',
    },
    {
      itemId: 11,
      category: 'getränke',
      itemName: 'Masala Chai',
      description: 'Würziger indischer Tee mit Milch und Gewürzen',
      price: 2.50,
      allergies: 'Enthält Milchprodukte',
    },
  ];